



<?php
/*
while($oferta = $todasOfertas -> fetchObject() ){
    echo "<h4>$oferta->titulo</h4> <br>";
    echo "<img src='uploads/img/$oferta->imagen'> <br>";
    echo " <br>$oferta->descripcion <br><br>" ;
    echo " <a href='index.php?c=Oferta&&a=delete&&id=$oferta->id'>Eliminar</a> <br>";
    echo " <a href='index.php?c=Oferta&&a=modificar&&id=$oferta->id'>Modificar</a><br>";
    echo "<br><br><hr>";
}
echo "<br> &nbsp; <a href='index.php'>Inicio</a>";
?>*/