<h1>Registrarse</h1>

<?php
if(isset($_GET['id'])){ 
    $oferta = $OfertaById->fetchObject();
    $titulo=$oferta->titulo;
    $imagen=$oferta->imagen;
    $descripcion=$oferta->descripcion;
    $submit="Actualizar";
    $action="index.php?c=Oferta&&a=NuevaOferta&&id=$oferta->id";
    
}else{
    $action="index.php?c=Oferta&&a=NuevaOferta";
    $titulo="";
    $imagen="";
    $descripcion="";
    $submit="Registrarse";
}
?>    
<form action="<?=$action?>" method="post" enctype="multipart/form-data">
    <label for="titulo">Titulo</label>
    <input type="text" name="titulo" value="<?=$titulo?>">
    
    <label for="imagen">Imagen</label>
    <?php 
    if(isset($_GET['id'])){?>
        <img src='uploads/img/<?=$imagen?>'>
    <?php
    }
    ?>
    <input type="file" name="imagen">
    
    <label for="descripcion">Descripcion</label>
    <textarea name="descripcion" id="descripcion"><?=$descripcion?></textarea>
    
    <input type="submit" name="submit" value="<?=$submit?>">
</form>
