<h1>Insertar Notas</h1>


<form action="index.php?c=Notas&&a=save" method="post">
    <label for="usuario_id">Usuario id</label>
    <input type="text" name="usuario_id" required>
    
    <label for="titulo">Titulo</label>
    <input type="text" name="titulo" required>
    
    <label for="descripcion">Descripcion</label>
    <input type="text" name="descripcion" required>
    
    <input type="submit" name="submit" value="Insertar">
</form>