<?php
require_once("views/mostrar/datos.phtml");
?>
<h1>Insertar</h1>

<form action="index.php?c=Datos&&a=save" method="post" onsubmit="return validar()">
    <label for="nombre">Name</label>
    <input type="text" name="Name" id="name" required>
    
    <label for="apellidos">Address</label>
    <input type="text" name="Address" id="address" required>
    
    <label for="descripcion">descripcion</label>
    <input type="text" name="descripcion" id="descripcion" required>
    
    <label for="telf">telf</label>
    <input type="tel" name="telf" id="telf" required>

    <label for="type">type</label>
    <input type="text" name="type" id="type" required>

    <input type="submit" name="submit" value="Registrarse">
</form>