<?php
require_once("views/mostrar/datos.phtml");

?>
<table class="table table-striped table-sm table-dark">
    <thead class="thead-light">
        <tr>
            <th scope="col">Identificador</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Telefono</th>
            <th scope="col">Tipo</th>
        </tr>
    </thead>
    <tbody>
<?php
    while ($datos = $Mostrar->fetchObject()){
        echo "<tr>" ;
        echo "<td scope='col'>". $datos->id . "</td>".
        "<td scope='col'>". $datos->name ."</td>".
        "<td scope='col'>". $datos->address ."</td>".
        "<td scope='col'>". $datos->descripcion ."</td>".
        "<td scope='col'>". $datos->telf . "</td>";
         if($datos->type=="p"){
            echo "<td scope='col'>"."Premium". "</td>"; 
        }else{
            echo "<td scope='col'>"."No Premium". "</td>"; 
        }
        echo "</tr>";
    }
?>
    </tbody>
</table>
